# Mec-mini-project 5.6.6, submitted by David Schonberger
## SQL at Scale with Spark SQL

Welcome to the SQL mini project. For this project, you will use the Databricks Platform and work through a series of exercises using Spark SQL. The dataset size may not be too big but the intent here is to familiarize yourself with the Spark SQL interface which scales easily to huge datasets, without you having to worry about changing your SQL queries. 

The data you need is present in the mini-project folder in the form of three CSV files. This data will be imported in Databricks to create the following tables under the __`country_club`__ database.

<br>
1. The __`bookings`__ table,
2. The __`facilities`__ table, and
3. The __`members`__ table.

You will be uploading these datasets shortly into the Databricks platform to understand how to create a database within minutes! Once the database and the tables are populated, you will be focusing on the mini-project questions.

In the mini project, you'll be asked a series of questions. You can solve them using the databricks platform, but for the final deliverable,
please download this notebook as an IPython notebook (__`File -> Export -> IPython Notebook`__) and upload it to your GitHub.

### Creating the Database

We will first create our database in which we will be creating our three tables of interest

In [ ]:
%sql 
drop database if exists country_club cascade;
create database country_club;
show databases;

databaseName
country_club
default

### Creating the Tables

In this section, we will be creating the three tables of interest and populate them with the data from the CSV files already available to you. 
To get started, first upload the three CSV files to the DBFS as depicted in the following figure

![](https://i.imgur.com/QcCruBr.png)


Once you have done this, please remember to execute the following code to build the dataframes which will be saved as tables in our database

In [ ]:
# File location and type
file_location_bookings = "/FileStore/tables/Bookings.csv"
file_location_facilities = "/FileStore/tables/Facilities.csv"
file_location_members = "/FileStore/tables/Members.csv"

file_type = "csv"

# CSV options
infer_schema = "true"
first_row_is_header = "true"
delimiter = ","

# The applied options are for CSV files. For other file types, these will be ignored.
bookings_df = (spark.read.format(file_type) 
                    .option("inferSchema", infer_schema) 
                    .option("header", first_row_is_header) 
                    .option("sep", delimiter) 
                    .load(file_location_bookings))

facilities_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_facilities))

members_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_members))

### Viewing the dataframe schemas

We can take a look at the schemas of our potential tables to be written to our database soon

In [ ]:
print('Bookings Schema')
bookings_df.printSchema()
print('Facilities Schema')
facilities_df.printSchema()
print('Members Schema')
members_df.printSchema()

Bookings Schema
root
 |-- bookid: integer (nullable = true)
 |-- facid: integer (nullable = true)
 |-- memid: integer (nullable = true)
 |-- starttime: timestamp (nullable = true)
 |-- slots: integer (nullable = true)

Facilities Schema
root
 |-- facid: integer (nullable = true)
 |-- name: string (nullable = true)
 |-- membercost: double (nullable = true)
 |-- guestcost: double (nullable = true)
 |-- initialoutlay: integer (nullable = true)
 |-- monthlymaintenance: integer (nullable = true)

Members Schema
root
 |-- memid: integer (nullable = true)
 |-- surname: string (nullable = true)
 |-- firstname: string (nullable = true)
 |-- address: string (nullable = true)
 |-- zipcode: integer (nullable = true)
 |-- telephone: string (nullable = true)
 |-- recommendedby: integer (nullable = true)
 |-- joindate: timestamp (nullable = true)

### Create permanent tables
We will be creating three permanent tables here in our __`country_club`__ database as we discussed previously with the following code

In [ ]:
permanent_table_name_bookings = "country_club.Bookings"
bookings_df.write.format("parquet").saveAsTable(permanent_table_name_bookings)

permanent_table_name_facilities = "country_club.Facilities"
facilities_df.write.format("parquet").saveAsTable(permanent_table_name_facilities)

permanent_table_name_members = "country_club.Members"
members_df.write.format("parquet").saveAsTable(permanent_table_name_members)

### Refresh tables and check them

In [ ]:
%sql
use country_club;
REFRESH table bookings;
REFRESH table facilities;
REFRESH table members;
show tables;

database,tableName,isTemporary
country_club,bookings,false
country_club,facilities,false
country_club,members,false

### Test a sample SQL query

__Note:__ You can use __`%sql`__ at the beginning of a cell and write SQL queries directly as seen in the following cell. Neat isn't it!

In [ ]:
%sql
select bookid, facid as facility_id, memid as member_id, starttime as start_time, slots from bookings limit 3

bookid,facility_id,member_id,start_time,slots
0,3,1,2012-07-03T11:00:00.000+0000,2
1,4,1,2012-07-03T08:00:00.000+0000,2
2,6,0,2012-07-03T18:00:00.000+0000,2

#### Q1: Some of the facilities charge a fee to members, but some do not. Please list the names of the facilities that do.

In [ ]:
%sql
select name, membercost as member_cost from facilities
where membercost > 0;

name,member_cost
Tennis Court 1,5.0
Tennis Court 2,5.0
Massage Room 1,9.9
Massage Room 2,9.9
Squash Court,3.5

####  Q2: How many facilities do not charge a fee to members?

In [ ]:
%sql
select count(facid) as number_of_facilities_free_to_members from facilities
where membercost = 0;

number_of_facilities_free_to_members
4

#### Q3: How can you produce a list of facilities that charge a fee to members, where the fee is less than 20% of the facility's monthly maintenance cost? 
#### Return the facid, facility name, member cost, and monthly maintenance of the facilities in question.

In [ ]:
%sql
select facid, name, membercost, monthlymaintenance from facilities
where membercost > 0 and membercost < .2 * monthlymaintenance;

facid,name,membercost,monthlymaintenance
0,Tennis Court 1,5.0,200
1,Tennis Court 2,5.0,200
4,Massage Room 1,9.9,3000
5,Massage Room 2,9.9,3000
6,Squash Court,3.5,80

#### Q4: How can you retrieve the details of facilities with ID 1 and 5? Write the query without using the OR operator.

In [ ]:
%sql
select facid, name, membercost, guestcost, initialoutlay, monthlymaintenance from facilities
where facid in (1,5);

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
1,Tennis Court 2,5.0,25.0,8000,200
5,Massage Room 2,9.9,80.0,4000,3000

#### Q5: How can you produce a list of facilities, with each labelled as 'cheap' or 'expensive', depending on if their monthly maintenance cost is more than $100? 
#### Return the name and monthly maintenance of the facilities in question.

In [ ]:
%sql
select name, monthlymaintenance, 
case when monthlymaintenance > 100 then 'Expensive' else 'Cheap' end as How_costly 
from facilities;

name,monthlymaintenance,How_costly
Tennis Court 1,200,Expensive
Tennis Court 2,200,Expensive
Badminton Court,50,Cheap
Table Tennis,10,Cheap
Massage Room 1,3000,Expensive
Massage Room 2,3000,Expensive
Squash Court,80,Cheap
Snooker Table,15,Cheap
Pool Table,15,Cheap

#### Q6: You'd like to get the first and last name of the last member(s) who signed up. Do not use the LIMIT clause for your solution.

In [ ]:
%sql
select distinct(concat(m.firstname, " " , m.surname)) as Full_name  
from members m inner join bookings b on m.memid = b.memid;

Full_name
Tracy Smith
John Hunt
Douglas Jones
Ramnaresh Sarwin
Ponder Stibbons
Anna Mackenzie
Darren Smith
Tim Rownam
Timothy Baker
Nancy Dare
Henrietta Rumney
Hyacinth Tupperware
Jemima Farrell
Janice Joplette
GUEST GUEST
Charles Owen
David Farrell
Joan Coplin
Henry Worthington-Smyth
Millicent Purview
David Jones
Erica Crumpet
Matthew Genting
Jack Smith
Tim Boothe
David Pinker
Florence Bader
Gerald Butters
Anne Baker
Burton Tracy

####  Q7: How can you produce a list of all members who have used a tennis court?
- Include in your output the name of the court, and the name of the member formatted as a single column. 
- Ensure no duplicate data
- Also order by the member name.

In [ ]:
%sql
select name, full_name from(
select distinct f.name, members.firstname, members.surname, concat(members.firstname, " " , members.surname) as full_name
from members
inner join bookings b on members.memid = b.memid
inner join facilities f on b.facid = f.facid
where f.name like "Tennis%"
order by concat(members.firstname, " " , members.surname));

name,full_name
Tennis Court 2,Anne Baker
Tennis Court 1,Anne Baker
Tennis Court 1,Burton Tracy
Tennis Court 2,Burton Tracy
Tennis Court 1,Charles Owen
Tennis Court 2,Charles Owen
Tennis Court 2,Darren Smith
Tennis Court 2,David Farrell
Tennis Court 1,David Farrell
Tennis Court 2,David Jones
Tennis Court 1,David Jones
Tennis Court 1,David Pinker
Tennis Court 1,Douglas Jones
Tennis Court 1,Erica Crumpet
Tennis Court 2,Florence Bader
Tennis Court 1,Florence Bader
Tennis Court 1,GUEST GUEST
Tennis Court 2,GUEST GUEST
Tennis Court 1,Gerald Butters
Tennis Court 2,Gerald Butters
Tennis Court 2,Henrietta Rumney
Tennis Court 2,Jack Smith
Tennis Court 1,Jack Smith
Tennis Court 1,Janice Joplette
Tennis Court 2,Janice Joplette
Tennis Court 2,Jemima Farrell
Tennis Court 1,Jemima Farrell
Tennis Court 1,Joan Coplin
Tennis Court 2,John Hunt
Tennis Court 1,John Hunt
Tennis Court 1,Matthew Genting
Tennis Court 2,Millicent Purview
Tennis Court 1,Nancy Dare
Tennis Court 2,Nancy Dare
Tennis Court 1,Ponder Stibbons
Tennis Court 2,Ponder Stibbons
Tennis Court 1,Ramnaresh Sarwin
Tennis Court 2,Ramnaresh Sarwin
Tennis Court 2,Tim Boothe
Tennis Court 1,Tim Boothe
Tennis Court 1,Tim Rownam
Tennis Court 2,Tim Rownam
Tennis Court 1,Timothy Baker
Tennis Court 2,Timothy Baker
Tennis Court 2,Tracy Smith
Tennis Court 1,Tracy Smith

#### Q8: How can you produce a list of bookings on the day of 2012-09-14 which will cost the member (or guest) more than $30? 

- Remember that guests have different costs to members (the listed costs are per half-hour 'slot')
- The guest user's ID is always 0. 

#### Include in your output the name of the facility, the name of the member formatted as a single column, and the cost.

- Order by descending cost, and do not use any subqueries.

In [ ]:
%sql
select  facilities.name as facility, concat(members.firstname, " " , members.surname) as full_name, 

case 
when bookings.memid = 0 
then bookings.slots * facilities.guestcost  
else bookings.slots * facilities.membercost
end as total_cost

from members
inner join bookings on members.memid = bookings.memid
inner join facilities on facilities.facid = bookings.facid

where extract(year from bookings.starttime) == 2012 and extract(month from bookings.starttime) = 9 and extract(day from bookings.starttime) = 14
and ((bookings.memid = 0 and bookings.slots * facilities.guestcost > 30) or (bookings.memid != 0 and bookings.slots * facilities.membercost > 30))

order by total_cost desc;

facility,full_name,total_cost
Massage Room 2,GUEST GUEST,320.0
Massage Room 1,GUEST GUEST,160.0
Massage Room 1,GUEST GUEST,160.0
Massage Room 1,GUEST GUEST,160.0
Tennis Court 2,GUEST GUEST,150.0
Tennis Court 2,GUEST GUEST,75.0
Tennis Court 1,GUEST GUEST,75.0
Tennis Court 1,GUEST GUEST,75.0
Squash Court,GUEST GUEST,70.0
Massage Room 1,Jemima Farrell,39.6
Squash Court,GUEST GUEST,35.0
Squash Court,GUEST GUEST,35.0

#### Q9: This time, produce the same result as in Q8, but using a subquery.

In [ ]:
%sql

select facilities.name as facility, concat(members.firstname, " " , members.surname) as full_name, members.memid, bookings.slots, facilities.membercost, facilities.guestcost,

(select slots * (case when bookings.memid = 0 and slots * guestcost > 30 then guestcost
when bookings.memid > 0 and slots * membercost > 30 then membercost
end)  
) as total_cost

from members
inner join bookings on members.memid = bookings.memid
inner join facilities on facilities.facid = bookings.facid
where extract(year from bookings.starttime) == 2012 and extract(month from bookings.starttime) = 9 and extract(day from bookings.starttime) = 14
and (select(case when bookings.memid = 0 and slots * guestcost > 30 then slots * guestcost
when bookings.memid > 0 and slots * membercost > 30 then slots * membercost
end)  
) is not null
order by total_cost;

facility,full_name,memid,slots,membercost,guestcost,total_cost
Squash Court,GUEST GUEST,0,2,3.5,17.5,35.0
Squash Court,GUEST GUEST,0,2,3.5,17.5,35.0
Massage Room 1,Jemima Farrell,13,4,9.9,80.0,39.6
Squash Court,GUEST GUEST,0,4,3.5,17.5,70.0
Tennis Court 1,GUEST GUEST,0,3,5.0,25.0,75.0
Tennis Court 1,GUEST GUEST,0,3,5.0,25.0,75.0
Tennis Court 2,GUEST GUEST,0,3,5.0,25.0,75.0
Tennis Court 2,GUEST GUEST,0,6,5.0,25.0,150.0
Massage Room 1,GUEST GUEST,0,2,9.9,80.0,160.0
Massage Room 1,GUEST GUEST,0,2,9.9,80.0,160.0
Massage Room 1,GUEST GUEST,0,2,9.9,80.0,160.0
Massage Room 2,GUEST GUEST,0,4,9.9,80.0,320.0

#### Q10: Produce a list of facilities with a total revenue less than 1000.
- The output should have facility name and total revenue, sorted by revenue. 
- Remember that there's a different cost for guests and members!

In [ ]:
%sql
select facilities.name, sum((case when bookings.memid = 0 then facilities.guestcost * bookings.slots
else facilities.membercost * bookings.slots
end)) as revenue

from facilities inner join bookings
on facilities.facid = bookings.facid

group by facilities.name

having sum((case when bookings.memid = 0 then facilities.guestcost * bookings.slots
else facilities.membercost * bookings.slots
end)) between 1 and 1000

order by revenue;

name,revenue
Table Tennis,180.0
Snooker Table,240.0
Pool Table,270.0